window.PREVIEWDIFF_VIDEO_EXAMPLES = [
  {
    id: '000002',
    title: 'Warm streetlights on snow',
    prompt: 'In a snowy nighttime setting, the streetlights cast a warm, orange glow over the quiet street.',
    category: 'Scene lighting',
    score: 4,
    previewdiff: 'img/videos/000002/previewdiff.mp4',
    previewdiffPoster: 'img/videos/000002/previewdiff_poster.webp',
    bon0: 'img/videos/000002/best_of_n_1.mp4',
    bon0Poster: 'img/videos/000002/best_of_n_1_poster.webp',
    bon1: 'img/videos/000002/best_of_n_2.mp4',
    bon1Poster: 'img/videos/000002/best_of_n_2_poster.webp'
  },
  {
    id: '000010',
    title: 'Passengers inside a train',
    prompt: 'In the interior of a brightly lit train, passengers sit along the sides while the window reveals the bustling subway station outside.',
    category: 'Scene composition',
    score: 4,
    previewdiff: 'img/videos/000010/previewdiff.mp4',
    previewdiffPoster: 'img/videos/000010/previewdiff_poster.webp',
    bon0: 'img/videos/000010/best_of_n_1.mp4',
    bon0Poster: 'img/videos/000010/best_of_n_1_poster.webp',
    bon1: 'img/videos/000010/best_of_n_2.mp4',
    bon1Poster: 'img/videos/000010/best_of_n_2_poster.webp'
  },
  {
    id: '000018',
    title: 'A plush bear among flowers',
    prompt: 'In a picturesque setting, surrounded by verdant hills and vibrant flowers, a plush bear stands among the blossoms.',
    category: 'Subject and setting',
    score: 4,
    previewdiff: 'img/videos/000018/previewdiff.mp4',
    previewdiffPoster: 'img/videos/000018/previewdiff_poster.webp',
    bon0: 'img/videos/000018/best_of_n_1.mp4',
    bon0Poster: 'img/videos/000018/best_of_n_1_poster.webp',
    bon1: 'img/videos/000018/best_of_n_2.mp4',
    bon1Poster: 'img/videos/000018/best_of_n_2_poster.webp'
  },
  {
    id: '000030',
    title: 'An overcast harbor becomes sunny',
    prompt: 'At a bustling harbor area, rows of colorful shipping containers are neatly aligned, and the sky is overcast. As the scene progresses, the clouds part, revealing a bright blue sky and bathing the containers in warm sunlight.',
    category: 'Weather transition',
    score: 4,
    previewdiff: 'img/videos/000030/previewdiff.mp4',
    previewdiffPoster: 'img/videos/000030/previewdiff_poster.webp',
    bon0: 'img/videos/000030/best_of_n_1.mp4',
    bon0Poster: 'img/videos/000030/best_of_n_1_poster.webp',
    bon1: 'img/videos/000030/best_of_n_2.mp4',
    bon1Poster: 'img/videos/000030/best_of_n_2_poster.webp'
  },
  {
    id: '000046',
    title: 'A gift box under changing lights',
    prompt: 'In a vibrant festival celebration, a gift box stands out on the decorated table, with the scene overall quite bright. Suddenly, the lights dim, shrouding the entire room in shadows. Then, various colorful flashes begin to illuminate the room, creating a dazzling spectacle.',
    category: 'Lighting transition',
    score: 4,
    previewdiff: 'img/videos/000046/previewdiff.mp4',
    previewdiffPoster: 'img/videos/000046/previewdiff_poster.webp',
    bon0: 'img/videos/000046/best_of_n_1.mp4',
    bon0Poster: 'img/videos/000046/best_of_n_1_poster.webp',
    bon1: 'img/videos/000046/best_of_n_2.mp4',
    bon1Poster: 'img/videos/000046/best_of_n_2_poster.webp'
  },
  {
    id: '000146',
    title: 'A camper van drives toward a trail',
    prompt: 'Under the late afternoon sun, a camper van is parked at the peaceful campground. Suddenly, the camper van\'s engine starts, and it begins to drive slowly towards the forest trail.',
    category: 'Action',
    score: 4,
    previewdiff: 'img/videos/000146/previewdiff.mp4',
    previewdiffPoster: 'img/videos/000146/previewdiff_poster.webp',
    bon0: 'img/videos/000146/best_of_n_1.mp4',
    bon0Poster: 'img/videos/000146/best_of_n_1_poster.webp',
    bon1: 'img/videos/000146/best_of_n_2.mp4',
    bon1Poster: 'img/videos/000146/best_of_n_2_poster.webp'
  },
  {
    id: '000154',
    title: 'Two dancers begin a routine',
    prompt: 'Under the vibrant stage lights, a pair of dancers stand gracefully in the center of the dance floor. After a moment of stillness, they begin to perform a lively and intricate dance routine.',
    category: 'Multi-person action',
    score: 4,
    previewdiff: 'img/videos/000154/previewdiff.mp4',
    previewdiffPoster: 'img/videos/000154/previewdiff_poster.webp',
    bon0: 'img/videos/000154/best_of_n_1.mp4',
    bon0Poster: 'img/videos/000154/best_of_n_1_poster.webp',
    bon1: 'img/videos/000154/best_of_n_2.mp4',
    bon1Poster: 'img/videos/000154/best_of_n_2_poster.webp'
  },
  {
    id: '000166',
    title: 'A woman puts on a hat',
    prompt: 'In a neat and bright clothing store, various hats are displayed, and a woman is walking around inside. Suddenly, the woman picks up a hat from a nearby shelf. Then, she puts the hat on her head.',
    category: 'Action sequence',
    score: 4,
    previewdiff: 'img/videos/000166/previewdiff.mp4',
    previewdiffPoster: 'img/videos/000166/previewdiff_poster.webp',
    bon0: 'img/videos/000166/best_of_n_1.mp4',
    bon0Poster: 'img/videos/000166/best_of_n_1_poster.webp',
    bon1: 'img/videos/000166/best_of_n_2.mp4',
    bon1Poster: 'img/videos/000166/best_of_n_2_poster.webp'
  },
  {
    id: '000242',
    title: 'A red tractor in a green field',
    prompt: 'In a sprawling agricultural setting, a red tractor stands idle in the middle of a vast green field.',
    category: 'Object and color',
    score: 4,
    previewdiff: 'img/videos/000242/previewdiff.mp4',
    previewdiffPoster: 'img/videos/000242/previewdiff_poster.webp',
    bon0: 'img/videos/000242/best_of_n_1.mp4',
    bon0Poster: 'img/videos/000242/best_of_n_1_poster.webp',
    bon1: 'img/videos/000242/best_of_n_2.mp4',
    bon1Poster: 'img/videos/000242/best_of_n_2_poster.webp'
  },
  {
    id: '000246',
    title: 'A rectangular outdoor pool',
    prompt: 'In the outdoor area of a modern house, a large, rectangular swimming pool glistens under the sunlight.',
    category: 'Scene geometry',
    score: 4,
    previewdiff: 'img/videos/000246/previewdiff.mp4',
    previewdiffPoster: 'img/videos/000246/previewdiff_poster.webp',
    bon0: 'img/videos/000246/best_of_n_1.mp4',
    bon0Poster: 'img/videos/000246/best_of_n_1_poster.webp',
    bon1: 'img/videos/000246/best_of_n_2.mp4',
    bon1Poster: 'img/videos/000246/best_of_n_2_poster.webp'
  }
];
